spring.application.name=webflow
server.port=8080

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/glccurlbase?currentSchema=glccurlschema
spring.datasource.username=postgres
spring.datasource.password=

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
